NAME=barber
CC=gcc                              			# překladač
CFLAGS=-std=gnu99 -Wall -Wextra -Werror -pedantic -lrt	# parametry překladače

	
$(NAME): $(NAME).c
	$(CC) $(CFLAGS) $(NAME).c -o $(NAME)
